import React from 'react';
import CodeTabs from '../../components/docs/CodeTabs';
import Callout from '../../components/docs/Callout';
import TableOfContents from '../../components/docs/TableOfContents';

const toc = [
  { id: 'overview', label: 'Overview', level: 2 },
  { id: 'node-types', label: 'Node Types', level: 2 },
  { id: 'pipeline-studio', label: 'Pipeline Studio', level: 2 },
  { id: 'ai-generation', label: 'AI Generation', level: 2 },
  { id: 'templates', label: 'Templates', level: 2 },
  { id: 'api', label: 'Workflow API', level: 2 },
];

export default function WorkflowsDocs() {
  return (
    <div className="flex">
      <div className="flex-1 max-w-3xl px-8 py-10">
        <div className="mb-2">
          <span className="text-xs text-[#00E5FF] font-medium">Core Concepts</span>
        </div>
        <h1 className="text-3xl font-bold text-white tracking-tight mb-2">Workflows</h1>
        <p className="text-white/40 text-sm mb-8">Workflows define the sequence of steps agents follow. Build them visually or let AI generate them.</p>

        <h2 id="overview" className="text-xl font-semibold text-white mt-8 mb-4 scroll-mt-20">Overview</h2>
        <p className="text-sm text-white/50 mb-4">
          A Workflow is a directed graph of nodes (steps) and edges (connections). Each node represents an action performed by an agent, and edges define the execution order. Workflows can be created manually in the Pipeline Studio, generated by AI, or defined via the API.
        </p>

        <h2 id="node-types" className="text-xl font-semibold text-white mt-10 mb-4 scroll-mt-20">Node Types</h2>
        <div className="space-y-2 mb-6">
          {[
            { type: 'Agent Node', color: '#3B82F6', desc: 'Assigns a step to a specific agent. The agent uses its tools and model to produce output.' },
            { type: 'Tool Node', color: '#10B981', desc: 'Directly invokes a tool (web search, code execution, etc.) without agent reasoning.' },
            { type: 'Condition', color: '#F59E0B', desc: 'Branching logic — routes the workflow based on the output of a previous step.' },
            { type: 'Approval Gate', color: '#EF4444', desc: 'Pauses execution until a human approves or rejects the pending action.' },
          ].map(n => (
            <div key={n.type} className="flex items-center gap-3 bg-white/[0.02] border border-white/[0.06] rounded-xl p-4">
              <div className="w-3 h-3 rounded-full flex-shrink-0" style={{ backgroundColor: n.color }} />
              <div>
                <h3 className="text-sm font-medium text-white">{n.type}</h3>
                <p className="text-xs text-white/45 mt-0.5">{n.desc}</p>
              </div>
            </div>
          ))}
        </div>

        <h2 id="pipeline-studio" className="text-xl font-semibold text-white mt-10 mb-4 scroll-mt-20">Pipeline Studio</h2>
        <p className="text-sm text-white/50 mb-4">
          The Pipeline Studio is a visual drag-and-drop editor for building workflows. Key features:
        </p>
        <ul className="space-y-2 text-sm text-white/50 mb-6">
          <li className="flex items-start gap-2"><span className="text-[#00E5FF]">•</span>Drag node types from the left panel onto the canvas</li>
          <li className="flex items-start gap-2"><span className="text-[#00E5FF]">•</span>Connect nodes by dragging between connection points</li>
          <li className="flex items-start gap-2"><span className="text-[#00E5FF]">•</span>Configure each node's agent, model, and tools in the right panel</li>
          <li className="flex items-start gap-2"><span className="text-[#00E5FF]">•</span>Pan the canvas by clicking and dragging the background</li>
          <li className="flex items-start gap-2"><span className="text-[#00E5FF]">•</span>Save and run workflows directly from the toolbar</li>
        </ul>

        <h2 id="ai-generation" className="text-xl font-semibold text-white mt-10 mb-4 scroll-mt-20">AI Generation</h2>
        <p className="text-sm text-white/50 mb-4">
          Describe what you want, and TentaOS will generate a complete workflow automatically:
        </p>
        <CodeTabs tabs={[
          { label: 'Dashboard', code: '# In Pipeline Studio, click "AI Generate"\n# Describe your workflow:\n"Research competitors, analyze their pricing,\nwrite a comparison report, and create a slide deck"' },
          { label: 'Python', code: `workflow = client.workflows.generate(\n    description="Research competitors, analyze pricing, "\n                "write comparison report, create slides",\n    pack="growth"\n)\n\nprint(f"Generated {len(workflow.nodes)} nodes")` },
          { label: 'CLI', code: `tentaos workflow generate \\\n  --desc "Research competitors, analyze pricing, write report" \\\n  --pack growth` },
        ]} />
        <Callout variant="info">
          AI-generated workflows can be edited in the Pipeline Studio after generation. Tweak agent assignments, add approval gates, or adjust the flow.
        </Callout>

        <h2 id="templates" className="text-xl font-semibold text-white mt-10 mb-4 scroll-mt-20">Templates</h2>
        <p className="text-sm text-white/50 mb-4">
          TentaOS includes pre-built workflow templates for common use cases:
        </p>
        <div className="grid grid-cols-2 gap-2 mb-6">
          {[
            { name: 'Content Pipeline', desc: 'Research → Write → Review → Publish' },
            { name: 'Code Review', desc: 'Analyze → Test → Review → Report' },
            { name: 'Market Research', desc: 'Search → Analyze → Summarize → Present' },
            { name: 'Data Processing', desc: 'Extract → Transform → Validate → Load' },
          ].map(t => (
            <div key={t.name} className="bg-white/[0.02] border border-white/[0.06] rounded-lg p-3">
              <p className="text-xs font-medium text-white/70">{t.name}</p>
              <p className="text-[10px] text-white/30 mt-0.5">{t.desc}</p>
            </div>
          ))}
        </div>

        <h2 id="api" className="text-xl font-semibold text-white mt-10 mb-4 scroll-mt-20">Workflow API</h2>
        <CodeTabs tabs={[
          { label: 'Python', code: `# Create workflow\nwf = client.workflows.create(\n    name="My Pipeline",\n    nodes=[\n        {"id": "1", "type": "agent", "agent": "researcher", "label": "Research"},\n        {"id": "2", "type": "agent", "agent": "writer", "label": "Write Report"},\n    ],\n    edges=[\n        {"id": "e1", "source": "1", "target": "2"}\n    ]\n)\n\n# Run workflow as a task\ntask = client.tasks.create(\n    goal="Execute my pipeline",\n    workflow_id=wf.id\n)` },
          { label: 'cURL', code: `curl -X POST "https://api.tentaos.ai/v1/workflows" \\\n  -H "Authorization: Bearer YOUR_KEY" \\\n  -d '{\n    "name": "My Pipeline",\n    "nodes": [...],\n    "edges": [...]\n  }'` },
        ]} />
      </div>
      <TableOfContents items={toc} />
    </div>
  );
}