import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

Deno.serve(async (req) => {
  const base44 = createClientFromRequest(req);
  const user = await base44.auth.me();
  if (!user) {
    return Response.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const { pipeline_name, content } = await req.json();
  if (!content) {
    return Response.json({ error: 'content is required' }, { status: 400 });
  }

  // Convert markdown to basic HTML
  const htmlContent = content
    .replace(/^### (.*$)/gm, '<h3>$1</h3>')
    .replace(/^## (.*$)/gm, '<h2>$1</h2>')
    .replace(/^# (.*$)/gm, '<h1>$1</h1>')
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/\n/g, '<br/>');

  const emailBody = `
    <div style="font-family: -apple-system, sans-serif; max-width: 680px; margin: 0 auto; background: #0a0a0f; color: #e0e0e0; padding: 32px; border-radius: 16px;">
      <div style="text-align: center; margin-bottom: 24px;">
        <h1 style="color: #00E5FF; font-size: 20px; margin: 0;">TentaOS Result</h1>
        <p style="color: #888; font-size: 13px; margin-top: 4px;">${pipeline_name || 'Pipeline Output'}</p>
      </div>
      <div style="background: #111118; border: 1px solid #222; border-radius: 12px; padding: 24px; font-size: 14px; line-height: 1.7;">
        ${htmlContent}
      </div>
      <p style="color: #555; font-size: 11px; text-align: center; margin-top: 20px;">
        Generated by TentaOS — Visual AI Operating System
      </p>
    </div>
  `;

  await base44.asServiceRole.integrations.Core.SendEmail({
    to: user.email,
    subject: "TentaOS: " + (pipeline_name || 'Pipeline Result'),
    body: emailBody,
    from_name: 'TentaOS',
  });

  return Response.json({ success: true, sent_to: user.email });
});