// @ts-nocheck
import React from 'react';
import { Link } from 'react-router-dom';
import useSEO from '@/lib/useSEO';
import LandingFooter from '@/components/landing/LandingFooter';

const LAST_UPDATED = 'May 12, 2026';

const AI_PROVIDER_DISCLAIMER =
  'TentaOS is an independent software platform and is not affiliated with OpenAI, Anthropic, Google, DeepSeek, or any other AI model provider. Third-party AI models may be used through their respective APIs to power AI-assisted workflows.';

const PAYMENT_DISCLAIMER =
  'Payments are processed by third-party payment providers. TentaOS does not store full card details.';

export default function Terms() {
  useSEO({
    title: 'Terms of Service — TentaOS',
    description:
      'Terms of Service for TentaOS by Wuhan Luojia Zhihui Technology Co., Ltd.',
    keywords: 'TentaOS, terms of service',
  });

  return (
    <div className="min-h-screen bg-[#06060B] text-white/85">
      <header className="border-b border-white/[0.06] px-6 py-5">
        <div className="max-w-3xl mx-auto flex flex-wrap items-center justify-between gap-3">
          <Link to="/Landing" className="text-sm text-[#00E5FF]/90 hover:text-[#00E5FF] transition-colors">
            ← Back to TentaOS
          </Link>
          <div className="flex items-center gap-4 text-xs text-white/35">
            <Link to="/privacy" className="hover:text-white/55">Privacy Policy</Link>
            <span className="text-white/15">·</span>
            <Link to="/refund" className="hover:text-white/55">Refund Policy</Link>
          </div>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-12 pb-20">
        <p className="text-[11px] uppercase tracking-wider text-white/35 mb-2">Legal</p>
        <h1 className="text-2xl font-semibold text-white tracking-tight mb-2">Terms of Service</h1>
        <p className="text-sm text-white/45 mb-10">
          These Terms govern your use of TentaOS offered by Wuhan Luojia Zhihui Technology Co., Ltd.
          <span className="block mt-1">Last updated: {LAST_UPDATED}</span>
        </p>

        <div className="space-y-10 text-sm text-white/65 leading-relaxed">
          <section className="space-y-3">
            <h2 className="text-base font-medium text-white">1. Use of service</h2>
            <p>
              Subject to these Terms, we grant you a limited, non-exclusive, non-transferable right to access and use
              TentaOS for your internal business or personal purposes in accordance with applicable law. You must not
              misuse the Product, interfere with its operation, or attempt unauthorized access to systems or data.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-medium text-white">2. Account responsibilities</h2>
            <p>
              You are responsible for safeguarding credentials and for all activity under your account. You agree to
              provide accurate information and to notify us promptly of any unauthorized use.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-medium text-white">3. AI output disclaimer</h2>
            <p>
              TentaOS may produce or orchestrate outputs generated by artificial intelligence models. Such outputs may be
              inaccurate, incomplete, or unsuitable for your purpose. You are solely responsible for evaluating and using
              outputs, including compliance with laws and third-party rights. We do not guarantee any particular result
              from AI-generated content.
            </p>
            <p className="text-white/55">{AI_PROVIDER_DISCLAIMER}</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-medium text-white">4. No illegal use</h2>
            <p>
              You may not use TentaOS for unlawful activities, to violate others’ rights, to distribute malware, to harass,
              or to generate content that infringes intellectual property or promotes illegal conduct.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-medium text-white">5. Payments</h2>
            <p className="text-white/55">{PAYMENT_DISCLAIMER}</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-medium text-white">6. Limitation of liability</h2>
            <p>
              To the maximum extent permitted by law, Wuhan Luojia Zhihui Technology Co., Ltd. and its affiliates will not
              be liable for any indirect, incidental, special, consequential, or punitive damages, or for loss of profits,
              data, or goodwill, arising from your use of TentaOS.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-medium text-white">7. Termination</h2>
            <p>
              We may suspend or terminate access to TentaOS if you materially breach these Terms or if required for legal or
              security reasons. You may stop using the Product at any time.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-medium text-white">8. Contact</h2>
            <p>
              For questions about these Terms:{' '}
              <a href="mailto:support@tentaos.com" className="text-[#00E5FF]/90 hover:text-[#00E5FF]">
                support@tentaos.com
              </a>
              .
            </p>
            <p className="text-white/45 text-xs">
              Company: Wuhan Luojia Zhihui Technology Co., Ltd. · Product: TentaOS
            </p>
          </section>
        </div>
      </main>

      <LandingFooter />
    </div>
  );
}
